1596: implement marker configuration in Standalone Map
VEuPathDB/web-monorepo pull request #111
Opened 2023-04-25 14:45 UTC by adnauseum

**Before**:

<img width="1512" alt="Screenshot 2023-04-25 at 9 45 50 AM" src="https://user-images.githubusercontent.com/24446573/234314516-6d187d41-b87b-46da-8a19-b287c726b607.png">

Here are the designs:

![image](https://user-images.githubusercontent.com/24446573/234679435-ceda434c-02a8-4770-bc77-da3e65cf1f49.png)
![image](https://user-images.githubusercontent.com/24446573/234679472-469fab24-888c-42d0-a376-04ce30388dea.png)

**After**:

https://user-images.githubusercontent.com/24446573/235502941-3268e476-2802-4dfc-a321-f9dfa08029e2.mp4

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/24446573/235535399-18e15ff8-6aad-476c-a011-5fcae0fca091.png">

2023-05-01 20:34 UTC, dmfalke commented
Screencast looks great! I will review the code as soon as I can (probably tonight).

2023-05-01 21:48 UTC, adnauseum commented on packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/BarPlotConfigurationMenu.tsx
> +      return;
<img width="727" alt="image" src="https://user-images.githubusercontent.com/24446573/235537346-db34a16e-950b-47dd-bb06-8734d5e7caad.png">

☝️ I imagine that we want to update this component to take a prop to hide the clear button. If not, I suppose we could select the study's default overlay variable.

2023-05-02 02:44 UTC, dmfalke requested changes
I think the code looks great. I have a couple of requested changes:

1. Make the "clear" button optional for `InputVariables`
2. Change the name of `DonutConfigurationMenu` to `DonutMarkerConfigurationMenu`, and `BarPlotConfigurationMenu` to `BarPlotMarkerConfigurationMenu`

2023-05-02 14:59 UTC, adnauseum commented on packages/libs/eda/src/lib/core/components/VariableLink.tsx
> +      props;
> Result of a formatting tool?
Yep, I was poking around that file, saved (muscle memory), and the new prettier config was applied 😄 

> Change the name of DonutConfigurationMenu to DonutMarkerConfigurationMenu, and BarPlotConfigurationMenu to BarPlotMarkerConfigurationMenu

Done in: 
* https://github.com/VEuPathDB/web-monorepo/pull/111/commits/4fd70ed3031a43ec79231995cca8461aa460266a
* https://github.com/VEuPathDB/web-monorepo/pull/111/commits/4ca19ee628642343271b9841588f2015163a4f05

> Make the "clear" button optional for InputVariables

Added in: https://github.com/VEuPathDB/web-monorepo/pull/111/commits/92e2d79a43ad4940161a3db3b9b162cc1e884744

🫡

2023-05-03 19:19 UTC, merged