Instant filters for the orthogroup page
VEuPathDB/web-monorepo pull request #1144
Opened 2024-07-19 15:02 UTC by bobular

Note that this targets `orthogroup-tree-table`, so can be merged without review.

Maybe we demo both or make a video with both?

2024-07-23 14:27 UTC, dmfalke commented
Sorry for the delay. I will take a look at this today or tomorrow

2024-07-26 14:20 UTC, dmfalke requested changes
I think the name of the new prop should be consistent with what we use for the checkbox select component. I'm fine with both being `instantUpdate`.

Also, I don't think `buttonDisplayContent` needs to be tracked with React state. I know this was already in place, but would be good to remove all unnecessary state and effects.

2024-07-26 14:20 UTC, dmfalke commented on packages/libs/coreui/src/components/inputs/SelectList.tsx
> +  }, [onChange, selected, instantUpdate]);
This should be called in a callback used as the `onChange` prop of `CheckboxList`. We don't currently have one defined, so it will be a new callback.

2024-08-02 18:02 UTC, bobular commented
Hi @dmfalke - thanks for the review.

I removed all but one effect thanks to your suggestion. While tesing things were still working in EDA/Lineplot I found a [new bug](https://github.com/VEuPathDB/web-monorepo/issues/1160) (already on qa and presumably prod) which I have a fix for too.

I don't think it's wise to get rid of the local state for `buttonDisplayContent `. The local state allows us to delay changing the button label until the drop-down is closed, which prevents it moving around as its contents change. I think this is OK.

2024-08-02 18:20 UTC, dmfalke commented
> I don't think it's wise to get rid of the local state for buttonDisplayContent . The local state allows us to delay changing the button label until the drop-down is closed, which prevents it moving around as its contents change. I think this is OK.

Makes sense. Thanks for checking!

2024-08-02 20:09 UTC, merged