Exclude multivalued vars from map markers overlay
VEuPathDB/web-monorepo pull request #236
Opened 2023-05-19 02:17 UTC by chowington

Fixes https://github.com/VEuPathDB/EdaNewIssues/issues/635

2023-05-19 19:14 UTC, bobular requested changes
Thanks. Works great but some streamlining recommended.

2023-05-25 13:56 UTC, chowington commented
Thanks Bob! It was working for me, which is odd because I agree those changes needed to be made. Note that a few variable selections simply seem to not work at all, like "indicator of specimen collection date discontinuity" and "Geolocation provenance"

2023-05-25 14:35 UTC, bobular commented
Indeed - I since noted that main is broken (my fault) until https://github.com/VEuPathDB/web-monorepo/pull/255 is merged.

I will test again right now and be careful with my choice of variables.

2023-05-25 15:22 UTC, bobular approved these changes
All seems good now, thanks!

The mouse-overs on the greyed out vars are not very helpful but I have opened another issue for this, as it requires some discussion and is not in scope here
https://github.com/VEuPathDB/EdaNewIssues/issues/644

2023-05-25 16:04 UTC, dmfalke commented on packages/libs/eda/src/lib/map/analysis/MarkerConfiguration/PieMarkerConfigurationMenu.tsx
>          selectedVariables={{ overlay: configuration.selectedVariable }}
Yep, `inputs[].name` should match up with keys of `selectedVariables`.

2023-05-25 20:33 UTC, merged