130 lineplot marginal histogram
VEuPathDB/web-monorepo pull request #290
Opened 2023-06-08 13:14 UTC by moontrip

This will address https://github.com/VEuPathDB/web-monorepo/issues/130 and https://github.com/VEuPathDB/web-monorepo/issues/131. Screenshots will be added in the following comment

Two new props are added to Lineplot component, `showMarginalHistogram` and `marginalHistogramSize`. The former decides to display marginal histogram in the Lineplot Viz and the latter is for the size of marginal histogram that has default value of 0.2 (20 %): Lineplot will take 80 %. Perhaps we need to adjust `showMarginalHistogram` prop to distinguish Lineplot Viz from Lineplot with marginal histogram Viz.

Tested many cases and all seem to work properly.

2023-06-08 13:22 UTC, moontrip commented
- ### GEMS1 with overlay using defalut binWidth
![marginal histogram30](https://github.com/VEuPathDB/web-monorepo/assets/12802305/d0468a3f-f373-48ff-8672-9032008c7a24)


- ### same to above but unchecked 24-59 months in the legend
![marginal histogram31](https://github.com/VEuPathDB/web-monorepo/assets/12802305/853bdc83-38cf-4100-8e9d-141fce6d8995)


- ### same to above but with a facet variable
![marginal histogram32](https://github.com/VEuPathDB/web-monorepo/assets/12802305/d5cb8e82-f859-4ede-8704-10bcab9f58eb)


- ### Same to above but binWidth is increased and custom axis ranges are applied to check
![marginal histogram4](https://github.com/VEuPathDB/web-monorepo/assets/12802305/067a9782-36b8-47ca-bdd3-070ce959e90c)


- ### testing filter for Age variable
![marginal histogram51](https://github.com/VEuPathDB/web-monorepo/assets/12802305/4889743b-b165-4368-b1a5-85d624068d78)


- ### Lineplot 0/0 case: example is taken from https://github.com/VEuPathDB/web-eda/issues/1082
![marginal histogram1](https://github.com/VEuPathDB/web-monorepo/assets/12802305/9fd7388a-f40a-4cd3-a36b-5ee6bd78b4ca)

2023-06-08 18:07 UTC, dmfalke commented
> Though, I am not quite sure where to place marginal histogram, top or bottom: a mockup suggested placing marginal histogram at the bottom of Lineplot, but examples we have seen and discussed in the meeting showed top area: personally, it looks better at top area.

I think one reason to put it on the bottom is so that is it closer to the x-axis ticks. Maybe @d-callan or @asizemore can weigh in?

2023-06-08 18:43 UTC, d-callan commented
It looks nice above. Can we duplicate the x-axis at the top of the line plot/ below the histo easily?

2023-06-08 18:47 UTC, moontrip commented
> It looks nice above. Can we duplicate the x-axis at the top of the line plot/ below the histo easily?

Thank you for your comment @d-callan 👍 I will try to see if I can add the x-axis.

2023-06-09 01:03 UTC, moontrip commented
@d-callan Here are some test results. Hope this will be useful for making a decision.
I have firstly checked a possibility of a tooltip described at https://github.com/VEuPathDB/web-monorepo/issues/151, but what I could achieve so far is to display a vertical line to cover up both plots. Tooltip contents are separately made depending on where a hover is located. Please see below two screenshots. Actually lineplot's tooltip contains the number of count (n).

- hovering histogram
![marginal histogram xaxis2 label04](https://github.com/VEuPathDB/web-monorepo/assets/12802305/d679ec0f-49b8-40b2-945a-6d057c5fcd44)

- hovering lineplot
![marginal histogram xaxis2 label03](https://github.com/VEuPathDB/web-monorepo/assets/12802305/2581c7fe-3f54-46cd-8904-b92cedd5e7c3)

I have also tested whether we can have xaxis tick labels at the bottom of histogram. I could manage to find a way to do that, but one disadvantage is that above tooltip cannot be used with this tick labels. It is because additional xaxis tick labels require additional definition of xaxis, saying xaxis2. Anyway please see below screenshots

- placing xaxis tick labels
![marginal histogram xaxis2 label01](https://github.com/VEuPathDB/web-monorepo/assets/12802305/545a0f9b-2b34-43ca-b1f4-4022a6b04ea1)

- Above may be okay but there is a possibility that lineplot's line/marker may be overlapped with those axis tick labels in some cases: though it is most likely okay because we have set that lineplot (and scatterplot) has some internal margin at the yaxis min and max area to avoid clipping of markers around those area. 
Anyway, I found a way to avoid such a case by slightly decrease Lineplot size, like below screenshot. Total plot sizes between above and below plots are identical, but lineplot size below has smaller size than the above, as you may notice.
![marginal histogram xaxis2 label02](https://github.com/VEuPathDB/web-monorepo/assets/12802305/6d0fb16a-9208-4767-8f10-6057bc41a323)

2023-06-09 01:42 UTC, d-callan commented
Thanks @moontrip. If we can't guarantee that both x axes are aligned then I favor the tooltip w dashed line. I think it's still ok to put the histo above. Nice job 👍

2023-06-09 03:24 UTC, moontrip commented
> Thanks @moontrip. If we can't guarantee that both x axes are aligned then I favor the tooltip w dashed line. I think it's still ok to put the histo above. Nice job 👍

@d-callan Thank you for your comment! After testing something more, I have one update concerning the positional difference of tick labels between xaxis and xaxis2, as seen earlier. I did not test many cases yet but such a difference is probably not an issue when drawing the plot via Viz because we have set the axis range: in the storybook examples above, I did not consider the range. Here is an example at Viz with the same data used at the storybook and the tick label positions seem to be identical each other. If you prefer aligned xaxis label, then I will check more cases carefully and implement it in this PR: if this is the case, one additional question is whether you want to have a gap in between lineplot and marginal histogram like below screenshot or without the gap.

![marginal histogram xaxis2 label05](https://github.com/VEuPathDB/web-monorepo/assets/12802305/25d07cf7-4dee-4f8e-ab5f-2181336c0986)

2023-06-09 09:46 UTC, d-callan commented
Can we see the regular tooltips? Remind me what they look like if we go for the duplicated x axis?

2023-06-09 12:57 UTC, moontrip commented
> Can we see the regular tooltips? Remind me what they look like if we go for the duplicated x axis?

@d-callan Yes, we will get regular tooltips that can be seen at either Histogram Viz (hovering histogram) or Lineplot Viz (hovering lineplot) if we use two individual x-axis. Below is an example for hovering Lineplot Viz's marker.

![marginal histogram xaxis2 label07](https://github.com/VEuPathDB/web-monorepo/assets/12802305/df2d2bd1-4936-4a7d-9745-dae6415bd96e)

2023-06-09 14:04 UTC, bobular commented
Reviewing now - but I suggest that linked tooltips be "future growth" i.e. another ticket.

2023-06-09 14:11 UTC, bobular commented
Do we prefer a tiny bit of spacing between the plots?

![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/fdaba09d-8ba0-4d01-ad6e-4ef96b132071)

2023-06-09 14:12 UTC, d-callan commented
I think the standard tooltip w duplicate x axis is fine, and that we should start without the gap between the two plots and see how much of an issue it really is in practice.

@bobular it's already a second ticket.

2023-06-09 14:32 UTC, moontrip commented
> I think the standard tooltip w duplicate x axis is fine, and that we should start without the gap between the two plots and see how much of an issue it really is in practice.
> 
> @bobular it's already a second ticket.

@d-callan Sounds good. I will make the change accordingly. 👍

2023-06-09 14:35 UTC, bobular requested changes
All looking good, but I'd like to test again and agree on some styling issues before we merge.

2023-06-09 14:35 UTC, bobular commented on packages/libs/components/src/plots/LinePlot.tsx
> +        // need to exclude marginal histogram
a better comment would be

```
// don't process tooltips for marginal histogram
```

But I am confused - where is `series.mode` set to non-null?  Seems like the consumer `LineplotVisualization` where the value is `'lines+markers'`.  This is a bit opaque.  Is there any way we can make it more self-explanatory?

I think at the minimum some very clear comments should be added. It seems like a specification for the props passed to this component is that if `showMarginalHistogram` is true, then a data series containing the histogram counts with undefined `mode`, must be provided.  Perhaps even validate the props to make sure this is the case.

2023-06-09 14:35 UTC, bobular commented on packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
> +              : ''),
Can this section be DRYed up?

2023-06-09 14:35 UTC, bobular commented on packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
> +                  (val as BinSampleSizeProportion).denominatorN
Just `denominatorN` here.  No fraction calculation.

2023-06-09 14:43 UTC, bobular commented
The slightly thicker top line (with no gap) bothers me in the storybook examples, but that doesn't seem to be a problem in the EDA. So I agree - no gap!

How about an axis label for the histogram?  "N"?  "Counts"?

2023-06-09 14:50 UTC, d-callan commented
Marginal plots often don't have an axis label, but I could go either way I guess..

2023-06-09 15:03 UTC, moontrip commented
> I have to say, it's a thing of beauty
> 
> ![image](https://user-images.githubusercontent.com/308639/244726418-552e81ea-fd95-4180-acba-72a2d5dd2753.png)

@bobular Thank you for your feedbacks earlier. I will address them. By the way, do you prefer x-axis tick labels for marginal histogram or without them like your screenshot?

2023-06-09 15:50 UTC, d-callan commented
Yes. If we don't have the axes duplicated I think the dotted line make it much more clear which values in the line plot are associated w a bin in the histo

2023-06-09 16:58 UTC, dmfalke reviewed
This is all looking great. Maybe next week we can discuss how to properly wire this up, using the `withOptions` functionality to reuse `LineplotVisualization` for the timeline plot.

2023-06-13 03:34 UTC, moontrip commented
@dmfalke I have defined `showMarginalHistogram` at visualizationPlugins (withOptions), https://github.com/VEuPathDB/web-monorepo/pull/290/commits/c3b51c90d04888dafe92c775d95f81891c115c6d. Technically, we don't necessarily do this for general lineplot Viz because I have set the default value as `false` at `LineplotVisualization` component if `options.showMarginalHistogram` is undefined, however, it may be better to explicitly define it for clarity.

I think that we may also use this new viz (line + marginal histogram) for standalone map's Viz. Although I did define `showMarginalHistogram` in there as well, it would require some additional work as I made a note in there (`standaloneVizPlugins.ts`).

2023-06-13 09:54 UTC, bobular requested changes
Marginal histograms are currently off everywhere.

I think we'll need a bit of back end work to define a timeline plot, right? It will need special constraints on the x axis.

2023-06-13 09:54 UTC, bobular commented on packages/libs/eda/src/lib/map/analysis/hooks/standaloneVizPlugins.ts
> +        // or define xxx.withOptions({}) directly at corresponding visualizationPlugins below
Yes I think we need to add `showMarginalHistogram` for just the appropriate lineplot(s).

2023-06-13 13:00 UTC, moontrip commented
@bobular Thank you for your comments 👍 Yes, I disabled lineplot with marginal histogram for at pass app but perhaps we need to enable it for the time being (testing etc.). I will do that.

2023-06-17 01:00 UTC, merged