Polishing updates for volcano plot
VEuPathDB/web-monorepo pull request #564
Opened 2023-10-24 10:51 UTC by asizemore

Resolves #558 

This PR improves the volcano plot styling and functionality in the following ways:
- Adds the `isClickable` prop to legends in order to control the cursor, preventing the legend from seeming clickable when it isn't but still allowing for the tooltip
- Updates the volcano legend text based on feedback from Dan B
- Added more space for the x axis annotations

In addition, this PR
- fixes the Empty plot volcano story and tooltip display names
- adds a new story that displays the volcano inside of our plot container. Helpful for checking out how the plot margins will look on the site.

2023-11-06 19:42 UTC, bobular requested changes
Sorry for the late review!

I think you only need the `isClickable` configuration prop for the "contents" of the legend not the title. Yes we show a pointy cursor, but that is to encourage the user to wait for the tooltip, not for them to click on it. So I think remove the bits that change the cursor for the title and the legend container.

`PlotLegend` handles the title, while the `PlotXXXLegend` components handle the contents. All the `PlotXXXLegend` components have the `isClickable` prop, so you can still pass this from `VolcanoPlotVisualization` and have `PlotListLegend` respond to it.

Let's check that the mouse cursor behaviour of regular visualizations (e.g. scatterplot with both types of overlay) are the same as qa before merging.

2023-11-06 19:42 UTC, bobular commented on packages/libs/eda/src/lib/core/components/visualizations/relaxMicrobe.tsx
😢

2023-11-06 19:42 UTC, bobular commented on packages/libs/components/src/components/plotControls/PlotLegend.tsx
> +  isClickable?: boolean;
I think remove this (explanation in final comments)

2023-11-09 11:25 UTC, asizemore commented
Update: decided to give pointer cursor only to items when they have the checkbox!

Also looping in @moontrip who i should have looped in from the start!

2023-11-10 13:23 UTC, bobular reviewed
Hi @asizemore 

I notice that for a vanilla visualization with a categorical legend, the whole legend panel has the :point_up_2: mouse cursor, including the title, which is not clickable.

I think the better solution would be to remove the `isClickable` prop from `PlotLegendBaseProps` and the `PlotLegend` component as a whole. In fact, remove `isClickable` from all the `PlotXXXLegend` components.  `PlotGradientLegend` and `PlotBubbleLegend` can hard-code `cursor: 'default'`.

Then in `PlotListLegend` the cursor attribute can be set something like this

`cursor: showCheckBox && item.hasData ? 'pointer' : 'default'`

2023-11-10 16:16 UTC, asizemore commented
@bobular Ready for another look!

The latest commit
- removes `isClickable`
- prevents checkbox items with no data (disabled checkbox items) from having the pointer and instead gives them the default cursor.

I checked the volcano legend and the vanilla scatterplot gradient and categorical legend - both functioned as expected. 

Let me know what you think!

2023-11-10 16:29 UTC, bobular approved these changes
Looks great. Confirmed functionality for mixed data/no-data checkbox legend :-)

2023-11-10 16:34 UTC, merged