add scale to EDA's display labels
VEuPathDB/web-monorepo pull request #721
Opened 2023-12-11 21:22 UTC by moontrip

This will address https://github.com/VEuPathDB/web-monorepo/issues/450.

It was hard to find where the scale info (metadata) is used but at least I could manage to find one study, Mal-ED study. After checking the codes carefully, I realized that an easy solution was to change `variableDisplayWithUnit()` so that all (or most) Vizs show scale info at various display labels such as axis title, legend title, variable coverage table etc. Below are screenshot with Scatterplot for before and after this PR.

I saw that there were cases where units are empty while scale exists. In that case, I just used scale with parenthesis: e.g., Polio serotype... in the "After" screenshot. 

### **- Before**
![MAL-ED scale01](https://github.com/VEuPathDB/web-monorepo/assets/12802305/f230c1f6-0311-471f-ad60-ac59ed1da8a7)

### **- After**
![MAL-ED scale01-PR](https://github.com/VEuPathDB/web-monorepo/assets/12802305/178d97a8-d0d2-485b-8c45-a527a5047a4d)

2024-01-05 15:45 UTC, dmfalke requested changes
Overall, this looks good. I added a suggested change, to simplify the code. Let me know what you think. Thanks!

2024-01-05 15:45 UTC, dmfalke commented on packages/libs/eda/src/lib/core/utils/variable-display.ts
> +  } else return variable?.displayName;
There is quite a bit of nesting of if-statements here. I think we can reduce the this significantly

```suggestion
  if (variable == null) return;
  if (!NumberVariable.is(variable)) return variable.displayName;
  
  const parentheticalParts = [ variable.units, variable.scale ].filter(Boolean);
  
  if (parentheticalParts.length) return `${variable.displayName} (${parentheticalParts.join(', ')})`;

  return variable.displayName;
```

2024-01-05 15:57 UTC, moontrip commented
> Overall, this looks good. I added a suggested change, to simplify the code. Let me know what you think. Thanks!

Hi again @dmfalke 👋 Thank you for your review and suggestion! I saw the technique, array.filter(Boolean), somewhere before and I think it would work quite well in this case. Will check it out next week 👍

2024-01-09 21:36 UTC, moontrip commented
@dmfalke I have addressed your feedbacks. It would be great if you can check it out 👍

2024-01-10 21:29 UTC, dmfalke approved these changes

2024-01-10 23:02 UTC, moontrip commented
Thank you for your review @dmfalke 👍

2024-01-10 23:02 UTC, merged