Tweak styles and incorporate "Add a Plot" into lefthand menu.
VEuPathDB/web-monorepo pull request #8
Opened 2023-03-23 15:48 UTC by adnauseum

Bob's most excellent PR (https://github.com/VEuPathDB/web-eda/pull/1690) brought in the ability for users to add a new visualization to the standalone map app. Hence the small _net_ diff.
 
This PR Piggybacks incorporates most of those components into the side navigation. 

A subsequent PR will break out the draggable panels! 🤘 

**Nota bene**:
- This PR includes Bob's addendum PR: #22 
- We should think about how we'll style the visualizations grid which is optimal for a lot of space.

<details>
<summary>See quick demo of the draggable panels here!</summary>

https://user-images.githubusercontent.com/24446573/228222505-5ebf7016-0f21-4ad7-98fd-2db7e1d6d163.mp4

</details>

**Before**:
<img width="1352" alt="Screenshot 2023-03-27 at 11 15 00 AM" src="https://user-images.githubusercontent.com/24446573/228001160-d7419901-f62b-45d4-adf6-5af90c53246a.png">
<img width="1352" alt="Screenshot 2023-03-27 at 11 14 51 AM" src="https://user-images.githubusercontent.com/24446573/228001182-81fd4fa8-1166-4954-8bbe-9a87ab02d8f6.png">

**After**:
<img width="1512" alt="Screenshot 2023-03-28 at 3 41 23 PM" src="https://user-images.githubusercontent.com/24446573/228361989-6af63683-06a0-487d-a34b-081ff2855bb1.png">

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/24446573/228048490-eb636749-c353-4e5f-99b5-ccb0434e2794.png">
<img width="1352" alt="Screenshot 2023-03-27 at 11 14 22 AM" src="https://user-images.githubusercontent.com/24446573/228001210-044af022-66b5-4724-8576-4e531125e693.png">

2023-03-27 19:46 UTC, adnauseum commented on packages/libs/eda/src/lib/map/analysis/FloatingVizManagement.tsx
> +      <div>
**Note to benevolent reviewer(s)**: the changes around here move the "Add a Plot" stuff into the side navigation. More than that, they also add some styling/verbiage tweaks discussed on [2023-03-23's Map UX meeting](https://veupathdb.atlassian.net/wiki/spaces/WG/pages/227573761/2023-03-23+Map+UX).

<img width="941" alt="Screenshot 2023-03-27 at 2 45 14 PM" src="https://user-images.githubusercontent.com/24446573/228049924-02b479ee-5c11-4703-9bc0-cd1e9a2ea4d1.png">

2023-03-27 19:49 UTC, adnauseum commented on packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> +} from '@material-ui/icons';
**Note to benevolent reviewer(s)**: these were added to flesh out the side navigation as per the discussed on [2023-03-23's Map UX meeting](https://veupathdb.atlassian.net/wiki/spaces/WG/pages/227573761/2023-03-23+Map+UX).

<img width="186" alt="image" src="https://user-images.githubusercontent.com/24446573/228050774-61bf8668-bc01-4bf8-bccb-0f350f605fd8.png">

2023-03-27 19:50 UTC, adnauseum commented on packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> +type App = {
**Question to benevolent reviewer(s)**: I wanted to get the type of `app`. This is copy/pasted from VS Code. What's the better way of doing this?

2023-03-27 19:53 UTC, adnauseum commented on packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> +  );
**Note to benevolent reviewer(s)**: this and following lines are changes made to the configuration and rendering of the lefthand side navigation items.

2023-03-28 14:24 UTC, bobular requested changes
Looks great.

At the moment, when a menu tab is activated, its component is rendered "afresh" via the `renderWithApp` function.

In order to get the "activeViz" inappropriately named `FullScreenVisualization` to persist when the menu item is closed, we're going to have to do some restructuring.

OR should we render all the menu tabs but only have the active one visible?

2023-03-28 16:02 UTC, adnauseum commented
> Looks great.
> 
> At the moment, when a menu tab is activated, its component is rendered "afresh" via the renderWithApp function.
> 
> In order to get the "activeViz" inappropriately named FullScreenVisualization to persist when the menu item is closed, we're going to have to do some restructuring (specifically: move the "activeViz" component out of this component into the parent MapAnalysis - actually this maybe isn't as problematic as I thought)
> 
> OR should we render all the menu tabs but only have the active one visible?

So this would be a scenario illustrating your thoughts:
* User clicks **Plot**.
* User selects a histogram and enters the name "My histo" without saving.
* User goes back to the side nav and pressed **Filter**.
* User does some awesome filtering! 👏 
* User clicks **Plot** again.
* _User should see their partially configured histogram with the name "My histo" in the editable name field_.

Right now the user returning to **Plot** would see everything reset.

2023-03-28 17:30 UTC, adnauseum commented on packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> +  );
Resolved in: https://github.com/VEuPathDB/web-monorepo/pull/8/commits/c853e0b19b033d59d553093b24d545c941190ada

2023-03-28 17:51 UTC, adnauseum commented on packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> +type App = {
Resolved by https://github.com/VEuPathDB/web-monorepo/pull/8/commits/73c5b41c7d1cfd0bed13bd0a782600c47a7a5fb2

2023-03-29 19:06 UTC, bobular approved these changes

2023-03-29 19:13 UTC, merged

2023-03-29 19:33 UTC, bobular commented
Re-requesting my own review because it looks like we need to leave this in a semi-attractive functional state before merging (so that I and maybe others can work on other menu items).

I suggest addressing only the following:

- [ ] all the new-plot icons fit on screen (or see [here](https://epvb.slack.com/archives/CMQ8K9XRS/p1680117273090959) for an alternative with fewer clicks)
- [ ] the floating plot in a draggable
- [ ] the activate floating plot highlighted in the list of plots
- [ ] make a new ticket for fine-tuned styling