Wire up redirect from legacy map to new map
VEuPathDB/web-monorepo pull request #936
Opened 2024-03-13 18:35 UTC by jernestmyers

Resolves #925

2024-03-15 19:53 UTC, dmfalke commented
I just started looking at this. I'm not seeing a modal, and it appears there are a couple of redirects going on. I see two POST requests to create an analysis, so I suspect that is why the modal isn't showing up. I will investigate more later.

2024-03-15 20:08 UTC, jernestmyers commented
Hmm, it works for me. I'm using these urls while testing:
`localhost:8080/a/app/workspace/maps/legacy-redirect-handler?signposts_ss=Pathogen&view=smpl&zoom_level=3&center=23.07973176244989,3.5156250000000004&summarizeBy=Sample%20type&grid=true&shared_link=true&limitTerms=true`

`localhost:8080/a/app/workspace/maps/legacy-redirect-handler`

`http://localhost:8080/a/app/workspace/maps/legacy-redirect-handler?signposts_ss=Pathogen&projectID=VBP0000812&view=smpl&zoom_level=4&center=26.82407078047018,45.08789062500001&summarizeBy=Project&grid=true&shared_link=true&limitTerms=true`

2024-03-18 14:42 UTC, dmfalke commented on packages/libs/web-common/src/controllers/LegacyMapRedirectHandler.tsx
> +      setHasCreatedAnalysis(true);
I'm thinking this should be set before creating the analysis, so that the state us updated as soon as possible.

2024-03-18 19:07 UTC, dmfalke requested changes
:rocket:

2024-03-18 19:08 UTC, dmfalke approved these changes
Didn't mean to request changes!

2024-03-18 22:14 UTC, merged

2024-03-19 12:04 UTC, bobular commented on packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> +  const [showRedirectModal, setShowRedirectModal] = useState(!!locationState);
Seems like we should be checking for the presence and truthiness of `locationState.showLegacyMapRedirectModal`?

2024-03-20 19:22 UTC, bobular commented on packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> +  const [showRedirectModal, setShowRedirectModal] = useState(!!locationState);
Maybe in the future it should be more like this, with some io-ts magic?
```
const locationState = location.state;
const [showRedirectModal, setShowRedirectModal] = useState(LegacyRedirectState.is(locationState) && locationState.showLegacyMapRedirectModal);
```

2024-04-02 14:32 UTC, jernestmyers commented on packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx
> +  const [showRedirectModal, setShowRedirectModal] = useState(!!locationState);
I've addressed this feedback in a new PR: https://github.com/VEuPathDB/web-monorepo/pull/983